### ISSUE TITLE
Sort by Level before loading

### ISSUE THREAD

**Issue by InfamousSky** [cswendrowski/FoundryVTT-Encounter-Builder#8]
It is currently not possible to filter results by level until the loading of actors has finished.
This is a problem for Systems with a lot of compendia with a shit ton of actors (like pf2e, thanks Paizo, our generous Gods), so loading takes around a minute or more, while that time could be reduced drastically if you are looking for an actor in a more specific range of levels.

**Comment by cswendrowski** [comment]
Due to how the code is currently structured, filtering can't occur before all of the Actors load.

Foundry v0.8.8 is a lot faster for Compendium loading changes, so give that a whirl. Otherwise, disable some of the Compendiums from loading at all in the Dungeon Moon module settings.

I hope you enjoy!

**Comment by cswendrowski** [comment]
Due to how the code is currently structured, filtering can't occur before all of the Actors load.

Foundry v0.8.8 is a lot faster for Compendium loading changes, so give that a whirl. Otherwise, disable some of the Compendiums from loading at all in the Dungeon Moon module settings.

I hope you enjoy!
